name: Test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test:
    # где зарускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
    # выкачиваем репозиторий
      - uses: actions/checkout@v4
    # настраиваем java
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: npm install -g bats
    # запускаем тесты
      - run: ./gradlew clean test
